### ISSUE TITLE
Segmentation fault when running asmhttpd

### ISSUE THREAD

**Issue by VioletFlare** [nemasu/asmttpd#30]
I wanted to test it, but it isn't working. I tried to use the release version but I'm getting the same error and no verbose debug information. What should I do?

sudo ./asmttpd web_root/
asmttpd - 0.4

Using Document Root: web_root/
Segmentation fault (core dumped)

**Comment by nemasu** [comment]
Hmm, that's odd. What version of Linux are you running?

**Comment by triforce** [comment]
If you have the knowledge to run gdb or strace and give us some more detail such as a stack trace that would also be useful.

**Comment by VioletFlare** [comment]
I'm running 
**OS:** Ubuntu 16.04 
**Kernel:** x86_64 Linux 4.4.0-83-generic

That's odd.
When I run the program from within gdb or strace the program works normally (I get a fully working server, it returns the contents of web_root without any problem) until I interrupt it.
Meanwhile, when I try to run it normally it returns the problem i mentioned.
So here's the core:

`gdb asmttpd -c core`

```
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from asmttpd...done.
[New LWP 3943]
[New LWP 3944]
[New LWP 3940]
[New LWP 3945]
[New LWP 3941]
[New LWP 3946]
[New LWP 3942]
Core was generated by `./asmttpd web_root/'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  sys_clone () at syscall.asm:219
219		push r14     ;Else,  set new return address
[Current thread is 1 (LWP 3943)]

```
Stack trace:

```
(gdb) thread apply all bt full

Thread 7 (LWP 3942):
#0  sys_accept () at syscall.asm:105
No locals.
#1  0x0000000000400c96 in sys_clone () at syscall.asm:216
No locals.
#2  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 6 (LWP 3946):
#0  sys_clone () at syscall.asm:217
No locals.
Backtrace stopped: Cannot access memory at address 0x7faa5ee96000

Thread 5 (LWP 3941):
#0  sys_accept () at syscall.asm:105
No locals.
#1  0x0000000000400c96 in sys_clone () at syscall.asm:216
No locals.
#2  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 4 (LWP 3945):
#0  sys_clone () at syscall.asm:219
No locals.
Backtrace stopped: Cannot access memory at address 0x7faa5ef9d000

Thread 3 (LWP 3940):
#0  sys_mmap_stack () at syscall.asm:202
No locals.
#1  0x0000000000400c96 in sys_clone () at syscall.asm:216
No locals.
#2  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 2 (LWP 3944):
#0  sys_accept () at syscall.asm:105
No locals.
#1  0x0000000000400c96 in sys_clone () at syscall.asm:216
No locals.
#2  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 1 (LWP 3943):
#0  sys_clone () at syscall.asm:219
No locals.
Backtrace stopped: Cannot access memory at address 0x7faa5f1a8000
```

I hope I provided enough information.
It is my frist time using it.

**Comment by reallyimeric** [comment]
It's wired but I will not get segfault when I run it with strace, like @VioletFlare ...

```
[x@x-x asmttpd]$ sudo strace ./asmttpd /tmp
execve("./asmttpd", ["./asmttpd", "/tmp"], 0x7ffd2409a428 /* 17 vars */) = 0
write(1, "asmttpd - 0.4\n\0", 15asmttpd - 0.4
)       = 15
write(1, "\n", 1
)                       = 1
write(1, "Using Document Root: \0\0\0\0\0\0\0", 28Using Document Root: ) = 28
write(1, "/tmp", 4/tmp)                     = 4
write(1, "\n", 1
)                       = 1
rt_sigaction(SIGINT, {sa_handler=0x40123e, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=NULL}, NULL, 8) = 0
rt_sigaction(SIGTERM, {sa_handler=0x40123e, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=NULL}, NULL, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=NULL}, NULL, 8) = 0
open("/tmp", O_RDONLY|O_DIRECTORY)      = 3
socket(AF_INET, SOCK_STREAM, IPPROTO_TCP) = 4
bind(4, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
listen(4, 100000000)                    = 0
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_GROWSDOWN, -1, 0) = 0x7fc2fcefc000
clone(child_stack=0x7fc2fcefc000, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|SIGCHLD) = 31880
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_GROWSDOWN, -1, 0) = 0x7fc2fcdf4000
clone(child_stack=0x7fc2fcdf4000, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|SIGCHLD) = 31881
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_GROWSDOWN, -1, 0) = 0x7fc2fccec000
clone(child_stack=0x7fc2fccec000, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|SIGCHLD) = 31882
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_GROWSDOWN, -1, 0) = 0x7fc2fcbe4000
clone(child_stack=0x7fc2fcbe4000, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|SIGCHLD) = 31883
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_GROWSDOWN, -1, 0) = 0x7fc2fcadc000
clone(child_stack=0x7fc2fcadc000, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|SIGCHLD) = 31884
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_GROWSDOWN, -1, 0) = 0x7fc2fc9d4000
clone(child_stack=0x7fc2fc9d4000, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|SIGCHLD) = 31885
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_GROWSDOWN, -1, 0) = 0x7fc2fc8cc000
clone(child_stack=0x7fc2fc8cc000, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|SIGCHLD) = 31886
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_GROWSDOWN, -1, 0) = 0x7fc2fc7c4000
clone(child_stack=0x7fc2fc7c4000, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|SIGCHLD) = 31887
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_GROWSDOWN, -1, 0) = 0x7fc2fc6bc000
clone(child_stack=0x7fc2fc6bc000, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|SIGCHLD) = 31888
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_GROWSDOWN, -1, 0) = 0x7fc2fc5b4000
clone(child_stack=0x7fc2fc5b4000, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|SIGCHLD) = 31889
nanosleep({tv_sec=10, tv_nsec=0}, 
```

**Comment by nemasu** [comment]
Hmm, I'm on 4.12.3 and it's working. Maybe I'll grab Ubuntu 17.04 and debug it.

**Comment by triforce** [comment]
Can you try running it through valgrind? It's not something trivial such as incorrect file permissions is it?

**Comment by nemasu** [comment]
@blackjack4494 @VioletFlare I downloaded a live ISO of Ubuntu 17.04, and I can't get it to segfault. Have you tried using the pre-built version on the releases page?

**Comment by blackjack4494** [comment]
@triforce https://gist.github.com/blackjack4494/99a520ecda4b5001eef069fd0e9a6575
I am even running this as root and another newly created user same result. I am using this on a server which is virtualized with qemu but shouldn't make any difference actually.

**Comment by nemasu** [comment]
@blackjack4494 It seem's that it's running out of stack space, except valgrind says the main thread stack size was 8388608 bytes ( or 8192 KB ), which is what I'm using.
Does ulimit -s return 8192? Also are there any syslogs or dmesg logs from the kernel related to this segfault? I'll try testing with qemu too, can you paste your machine options?

**Comment by nemasu** [comment]
Wow, I just started getting this error myself.

Ran it through valgrind:
>==15942== Thread 2:
==15942== Invalid write of size 8
==15942==    at 0x400C9C: ??? (syscall.asm:219)
==15942==  Address 0x47ffff8 is on thread 2's stack
==15942== 
==15942== 
==15942== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==15942==  Access not within mapped region at address 0x47FFFF8
==15942==    at 0x400C9C: ??? (syscall.asm:219)

Tried increasing the stack size of child processes, but didn't work.

**Comment by triforce** [comment]
What kernel version are you using @nemasu?

**Comment by nemasu** [comment]
4.12.3 still, was working before. The only difference I can think of is than my machine is under heavy load. When I restart I'll try again and see if it makes any difference.

**Comment by will-riley** [comment]
Same segfault, symptoms. Runs under strace. Valgrind shows same Invalid write of size 8.
4.9.34-gentoo

**Comment by nemasu** [comment]
It seems to crash under strace sometimes too:

```
[pid 32555] mmap(NULL, 163840, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_GROWSDOWN, -1, 0) = 0x7fc050eb6000
....
[pid 32555] clone(child_stack=0x7fc050eb6000, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|SIGCHLD) = 32570
....
[pid 32570] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7fc050eb5ff8} ---
```

It seems to be accessing the correct address when it crashes...

**Comment by triforce** [comment]
Is there anything we can actually do to prevent this from happening?

**Comment by nemasu** [comment]
There must be a problem or bug somewhere...I've been looking, but still nothing.

**Comment by nemasu** [comment]
Yay! I think I fixed it, please pull, rebuild and try again. I will close this issue soon.

**Comment by will-riley** [comment]
Works! Bravo
